/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package noir;

public class App {
    // This declares that the static `hello` method will be provided
    // a native library.
    private static native String hello(String input);
    
    static {
        // This actually loads the shared object that we'll be creating.
        // The actual location of the .so or .dll may differ based on your
        // platform.
        System.loadLibrary("noir_java");
    }

    // The rest is just regular ol' Java!
    public static void main(String[] args) {
        String output = App.hello("josh");
        System.out.println(output);
    }
}
